"""initial_schema_all_7_tables

Revision ID: 7a6b1e776e8f
Revises:
Create Date: 2026-03-26 05:17:58.044477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7a6b1e776e8f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "style_presets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("preview_url", sa.Text(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "idx_style_presets_active", "style_presets", ["is_active"], unique=False
    )
    op.create_index(
        "idx_style_presets_category", "style_presets", ["category"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("clerk_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("plan", sa.String(length=20), server_default="free", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clerk_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("idx_users_clerk_id", "users", ["clerk_id"], unique=False)
    op.create_index("idx_users_email", "users", ["email"], unique=False)
    op.create_table(
        "stories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_stories_status", "stories", ["status"], unique=False)
    op.create_index("idx_stories_user_id", "stories", ["user_id"], unique=False)
    op.create_table(
        "episodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("story_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column(
            "target_duration_sec", sa.Integer(), server_default="90", nullable=False
        ),
        sa.Column("visual_style_id", sa.Uuid(), nullable=True),
        sa.Column("voice_style_id", sa.Uuid(), nullable=True),
        sa.Column("music_style_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column(
            "composition_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("final_video_url", sa.Text(), nullable=True),
        sa.Column(
            "final_video_duration_sec", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column("script_pdf_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["music_style_id"],
            ["style_presets.id"],
        ),
        sa.ForeignKeyConstraint(["story_id"], ["stories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["visual_style_id"],
            ["style_presets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voice_style_id"],
            ["style_presets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_episodes_status", "episodes", ["status"], unique=False)
    op.create_index("idx_episodes_story_id", "episodes", ["story_id"], unique=False)
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("episode_id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=30), nullable=False),
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column(
            "progress",
            sa.Numeric(precision=5, scale=2),
            server_default="0",
            nullable=True,
        ),
        sa.Column("stage", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_gen_jobs_celery", "generation_jobs", ["celery_task_id"], unique=False
    )
    op.create_index(
        "idx_gen_jobs_episode_id", "generation_jobs", ["episode_id"], unique=False
    )
    op.create_index("idx_gen_jobs_status", "generation_jobs", ["status"], unique=False)
    op.create_table(
        "scenes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("episode_id", sa.Uuid(), nullable=False),
        sa.Column("scene_order", sa.Integer(), nullable=False),
        sa.Column("beat_label", sa.String(length=50), nullable=False),
        sa.Column("visual_description", sa.Text(), nullable=False),
        sa.Column("narration_text", sa.Text(), nullable=True),
        sa.Column("dialogue_text", sa.Text(), nullable=True),
        sa.Column("duration_sec", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("image_prompt", sa.Text(), nullable=True),
        sa.Column("start_frame", sa.Integer(), nullable=True),
        sa.Column("end_frame", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("episode_id", "scene_order"),
    )
    op.create_index("idx_scenes_episode_id", "scenes", ["episode_id"], unique=False)
    op.create_index(
        "idx_scenes_order", "scenes", ["episode_id", "scene_order"], unique=False
    )
    op.create_table(
        "video_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scene_id", sa.Uuid(), nullable=False),
        sa.Column("asset_type", sa.String(length=20), nullable=False),
        sa.Column("file_url", sa.Text(), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_video_assets_active",
        "video_assets",
        ["scene_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "idx_video_assets_scene_id", "video_assets", ["scene_id"], unique=False
    )
    op.create_index(
        "idx_video_assets_type", "video_assets", ["asset_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_video_assets_type", table_name="video_assets")
    op.drop_index("idx_video_assets_scene_id", table_name="video_assets")
    op.drop_index("idx_video_assets_active", table_name="video_assets")
    op.drop_table("video_assets")
    op.drop_index("idx_scenes_order", table_name="scenes")
    op.drop_index("idx_scenes_episode_id", table_name="scenes")
    op.drop_table("scenes")
    op.drop_index("idx_gen_jobs_status", table_name="generation_jobs")
    op.drop_index("idx_gen_jobs_episode_id", table_name="generation_jobs")
    op.drop_index("idx_gen_jobs_celery", table_name="generation_jobs")
    op.drop_table("generation_jobs")
    op.drop_index("idx_episodes_story_id", table_name="episodes")
    op.drop_index("idx_episodes_status", table_name="episodes")
    op.drop_table("episodes")
    op.drop_index("idx_stories_user_id", table_name="stories")
    op.drop_index("idx_stories_status", table_name="stories")
    op.drop_table("stories")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_index("idx_users_clerk_id", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_style_presets_category", table_name="style_presets")
    op.drop_index("idx_style_presets_active", table_name="style_presets")
    op.drop_table("style_presets")
    # ### end Alembic commands ###
